spring:
    profiles:
        active: 
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        driver-class-name: ${PROD_DB_DRIVER_CLASS_NAME}
        url: ${PROD_DB_URL}
        username: ${PROD_DB_USER_NAME} 
        password: ${PROD_DB_PASSWORD}

server:
    servlet:
        encoding:
            force-response: true

jwt:
    token:
        secret: ${JWT_TOKEN_SECRET}
      