server:
    servlet:
        encoding:
            force-response: true

spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        driver-class-name: ${DB_DRIVER_CLASS_NAME}
        url: ${DB_URL}
        username: ${DB_USER_NAME} 
        password: ${DB_PASSWORD}

jwt:
    token:
        secret: ${JWT_TOKEN_SECRET}
      